add `tapBoth`
Effect-TS/stream pull request #157
Opened 2023-08-14 10:55 UTC by fubhy

2023-08-15 09:10 UTC, tim-smart requested changes

2023-08-15 09:10 UTC, tim-smart commented on src/internal/stream.ts
> +      catchAll((error) => fromEffect(Effect.zipRight(onFailure(error as any), Effect.fail(error))))
This will also catch the errors from the onSuccess effect?

There should be an operator that allows you to map over a lower level result.

2023-08-15 09:16 UTC, fubhy commented on src/internal/stream.ts
> +      catchAll((error) => fromEffect(Effect.zipRight(onFailure(error as any), Effect.fail(error))))
Ah good point. Will look into that when i am back at my desk

2023-08-15 18:55 UTC, fubhy commented on src/internal/stream.ts
> +      catchAll((error) => fromEffect(Effect.zipRight(onFailure(error as any), Effect.fail(error))))
Hm... Not sure if I'm missing sth. after all: The test I just added suggests that it's good as is unless I misunderstood your review feedback.

2023-08-15 19:29 UTC, tim-smart commented on src/internal/stream.ts
> +      catchAll((error) => fromEffect(Effect.zipRight(onFailure(error as any), Effect.fail(error))))
Ah yeah, I meant that it **shouldn't** catch errors from the `onSuccess` effect.

2023-08-16 08:16 UTC, fubhy commented on src/internal/stream.ts
> +      catchAll((error) => fromEffect(Effect.zipRight(onFailure(error as any), Effect.fail(error))))
So swapping the instructions should be sufficient then, no? If not, can you give me a hint which operator you were referring to?

2023-08-16 09:03 UTC, tim-smart requested changes

2023-08-16 09:03 UTC, tim-smart commented on src/internal/stream.ts
> +      catchAll((error) => fromEffect(Effect.zipRight(onFailure(error as any), Effect.fail(error)))),
Hah now you have the opposite problem, the success values of `onFailure` will be piped through `onSuccess`.

I think to implement this correctly you will need to use Channels and something like `readWithCause`.

2023-08-16 09:04 UTC, fubhy commented on src/internal/stream.ts
> +      catchAll((error) => fromEffect(Effect.zipRight(onFailure(error as any), Effect.fail(error)))),
Ok I've seen that but it "looked" like a lot of overhead. :-). Will take a stab at it though!

2023-08-17 18:15 UTC, fubhy commented
@tim-smart I went back to ZIO and stole their implementation & test cases. Is this heading in the right direction now? ;-)

2023-08-17 18:31 UTC, tim-smart approved these changes

2023-08-17 18:31 UTC, merged

2023-08-17 18:32 UTC, tim-smart commented
Looks good thanks.